### ISSUE TITLE
questions about training time

### ISSUE THREAD

**Issue by EcustBoy** [OpenDriveLab/ST-P3#1]
Hi  author~ I would like to ask how long your training time is. 
I used the same GPU configuration (V100 * 4) and the same training parameters (except for batch size，I set batch size =1 because of limitation of GPU) as in your paper,  run the original code, train the whole end to end model directly without pretrained perception model.

Then I found that an epoch takes about 25h.  Besides, as the epoch increases, the time-consuming of each iteration in one epoch also increases,  The following picture shows the recording during the training process， it doesn't look normal. Is this possible because the pretrained perception model is not loaded？or batch_size =1 is too small?
![image](https://user-images.githubusercontent.com/32817744/180697243-901b0ffc-229c-49d3-b188-8a189d0d0760.png)

Can you offer some suggestions for improvement? thanks~

**Comment by ilnehc** [comment]
@EcustBoy It seems indeed abnormal. We can train the model in around 3 days, with 3-4s/it, even on the cluster which may hamper the training speed due to IO limitation. Could you try with other machines/GPUs to see if the problem still exits? You probably can try to profile the code to see which part takes that long time as well.
