### ISSUE TITLE
Dear author ,some question about param

### ISSUE THREAD

**Issue by emilyemliyM** [OpenDriveLab/ST-P3#3]
1)what does "annotation['visibility_token']) == 1" mean?  is that means that we will filter the low visibility car?

2)What's more, since the depth images can not be accessed ,If I produce the depth by myself, what's the revolution I should save ? "1600*900"  or "224*480" or any other?

Really thanks.

**Comment by charleshsc** [comment]
1) It is mentioned in the nuScenes dataset that "The visibility of an instance is the fraction of annotation visible in all 6 images. Binned into 4 bins 0-40%, 40-60%, 60-80% and 80-100%." Yeah, we filter the low visibility car.

2) If you want to produce by yourself, my suggestion is to generate a depth image of the same size as the original image (1600 x 900), so that the original image and the depth image can be kept the same scale during subsequent image processing. You can also generate small depth images(224 x 480) directly if you can ensure that the depth image scale is correct.
