### ISSUE TITLE
Dear author, questions about depth gt 

### ISSUE THREAD

**Issue by emilyemliyM** [OpenDriveLab/ST-P3#6]
I see the depth gt labels is got by the slice operation below:

depth_labels = depths[:, :self.model.receptive_field, :, ::self.model.encoder_downsample,
                           ::self.model.encoder_downsample]

So why is it got by slice operation instead  "the encorder"? 

Really thanks

**Comment by charleshsc** [comment]
At the beginning, we first obtain the estimated value of depth by other methods and use it as the gt value of the depth. Note that the depth data obtained at this time is consistent with the size of the original image. (1600 x 900)

Note that the input image goes through the resize process, in order to ensure the consistency the depth data also goes through it, which is 
"
depth_labels = depths[:, :self.model.receptive_field, :, ::self.model.encoder_downsample,
::self.model.encoder_downsample]
"

We consider it as the label and no need for further processing of this data except for the resize(slice operation).
